import type { DagNode } from "../../../contracts/contractTypes.js";
import { InputSchema, OutputSchema, type Input, type Output } from "./contract.js";

function escapeMarkdown(value: string): string {
  return value.replaceAll("|", "\\|");
}

function formatList(items: string[]): string {
  if (items.length === 0) {
    return "None";
  }

  return items.map((item) => `\`${escapeMarkdown(item)}\``).join(", ");
}

function describeNode(node: DagNode): string {
  return [
    `## ${escapeMarkdown(node.id)}`,
    "",
    `- **Kind:** \`${node.kind}\``,
    `- **Status:** \`${node.status}\``,
    `- **What it does:** ${escapeMarkdown(node.purpose)}`,
    `- **Input it expects:** \`${escapeMarkdown(node.inputSchema)}\``,
    `- **Output it gives:** \`${escapeMarkdown(node.outputSchema)}\``,
    `- **Dependencies:** ${formatList([...node.dependencies].sort())}`,
    "- **Invariants:**",
    ...node.invariants.map((invariant) => `  - ${escapeMarkdown(invariant)}`),
    `- **Allowed files:** ${formatList([...node.allowedFiles].sort())}`,
    ""
  ].join("\n");
}

export function run(input: Input): Output {
  const parsedInput = InputSchema.parse(input);
  const nodes = [...parsedInput.dag.nodes].sort((left, right) => left.id.localeCompare(right.id));
  const title = parsedInput.title ?? "Functional DAG Node Catalog";
  const markdown = [
    `# ${escapeMarkdown(title)}`,
    "",
    "<!-- Generated by npm run generate:docs. Do not edit by hand. -->",
    "",
    "This catalog is generated from `specs/dag.json`. Update the DAG first, then regenerate this file.",
    "",
    ...nodes.map(describeNode)
  ].join("\n");

  return OutputSchema.parse({ markdown });
}
