import { describe, expect, it } from "vitest";
import type { Dag } from "../../../contracts/contractTypes.js";
import { run } from "./implementation.js";

const dag: Dag = {
  nodes: [
    {
      id: "b",
      kind: "imperative",
      purpose: "Write the generated artifact to disk through a shell boundary.",
      inputSchema: "markdown, outputPath",
      outputSchema: "written file",
      dependencies: ["a"],
      invariants: ["Imperative shell helper may write only the generated artifact."],
      allowedFiles: ["tools/generate-node-docs.ts", "specs/node_catalog.md"],
      status: "verified"
    },
    {
      id: "a",
      kind: "pure",
      purpose: "Build a stable generated document from the DAG node metadata.",
      inputSchema: "Dag",
      outputSchema: "Markdown document",
      dependencies: [],
      invariants: ["The function is pure and deterministic."],
      allowedFiles: ["src/nodes/a/contract.ts"],
      status: "verified"
    }
  ]
};

describe("buildNodeCatalog", () => {
  it("generates one clear section per node", () => {
    const result = run({ dag, title: "Node Docs" });

    expect(result.markdown).toContain("# Node Docs");
    expect(result.markdown).toContain("<!-- Generated by npm run generate:docs. Do not edit by hand. -->");
    expect(result.markdown).toContain("## a");
    expect(result.markdown).toContain("## b");
    expect(result.markdown).toContain("**What it does:** Build a stable generated document");
    expect(result.markdown).toContain("**Input it expects:** `Dag`");
    expect(result.markdown).toContain("**Output it gives:** `Markdown document`");
  });

  it("sorts nodes by id for stable generated output", () => {
    const result = run({ dag });

    expect(result.markdown.indexOf("## a")).toBeLessThan(result.markdown.indexOf("## b"));
  });
});
